language: ruby
gemfile:
  - Gemfile
rvm:
  - "1.9.2"
  - "1.9.3"
  - "2.0.0"
before_script:
  - cp config/database.yml.sample config/database.yml
  - rm db/seeds.rb
  - mv db/seeds.travis.rb db/seeds.rb
script:
  - bundle exec rake db:migrate
  - bundle exec rake db:load_test_data
