language: ruby
gemfile:
- Gemfile
env:
- TRAVIS_NODE_VERSION="7.4.0"
install:
- rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm
  && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm
  install $TRAVIS_NODE_VERSION
- bundle install --jobs=3 --retry=3 --deployment
before_script:
- mv .env.travis .env
- cp config/database.yml.sample config/database.yml
- psql -c 'create database teikei_test;' -U postgres
- rm db/seeds.rb
- mv db/seeds.travis.rb db/seeds.rb
- cd client && npm install && cd ..
script:
- bundle exec rake db:migrate
- bundle exec rake spec
bundler_args: "--without production"
sudo: false
cache: bundler
after_success:
- mkdir -p config/deploy
- openssl aes-256-cbc -K $encrypted_b8cfafe2545a_key -iv $encrypted_b8cfafe2545a_iv
  -in deployment_config.tar.gz.enc -out deployment_config.tar.gz -d
- tar xvzf deployment_config.tar.gz
- mv config/deploy/staging_travis.rb config/deploy/staging.rb
- eval `ssh-agent -s`
- ssh-add config/deploy/teikei_rsa
- bundle exec cap staging deploy
notifications:
  slack:
    secure: UL7Lg5WVq7WnO/LHgwG7YvThEfKKoHW3izwVnxksudh2A1n5uwAOYvVM2qloeFUCDHjNMDkrUsNL3IV04YJeSOmbzCJDAAvASVP5HGIaB6/Ex8EmyIugWYRRqOYyWIFWepvbf3MF0CccVvIp1RMH0B2zZXqSgsppAGerc3se9dc=
